"""initial schema

Revision ID: b804630ed86a
Revises: 
Create Date: 2026-10-01 17:47:41.801983
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b804630ed86a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('engagement_ref', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('parent_asset_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=4096), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('source_tool', sa.String(length=64), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('privilege_level', sa.Integer(), nullable=False),
    sa.Column('cookies', sa.JSON(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('storage_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=4096), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('cwe_id', sa.String(length=32), nullable=True),
    sa.Column('owasp_category', sa.String(length=128), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tool_source', sa.String(length=64), nullable=False),
    sa.Column('poc_steps', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('http_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('auth_context_id', sa.Integer(), nullable=True),
    sa.Column('origin_transaction_id', sa.Integer(), nullable=True),
    sa.Column('tool_source', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('url', sa.String(length=4096), nullable=False),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_length', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['auth_context_id'], ['auth_contexts.id'], ),
    sa.ForeignKeyConstraint(['origin_transaction_id'], ['http_transactions.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload_used', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('http_transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['http_transaction_id'], ['http_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secret_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('http_transaction_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('matched_value', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('promoted_finding_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['http_transaction_id'], ['http_transactions.id'], ),
    sa.ForeignKeyConstraint(['promoted_finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secret_matches')
    op.drop_table('evidence')
    op.drop_table('http_transactions')
    op.drop_table('findings')
    op.drop_table('reports')
    op.drop_table('auth_contexts')
    op.drop_table('assets')
    op.drop_table('targets')
    # ### end Alembic commands ###
